name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *' # Update setiap hari
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: '🪄 Auto Updates Readme file WakaTime Status'
          HIDE: "storage,repositories,contributions,hiring,profileViews"
          SHOW_TITLE: "False"
          SHOW_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False" 
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"